### ISSUE TITLE
Model cannot be saved when k2 = 0

### ISSUE THREAD

**Issue by jilljenn** [jfloff/pywFM#24]
When the latent dimension is 0, `libFM` still performs training but the pywFM can't save the model.

Code:

    fm = pywFM.FM(task='classification', num_iter=5, k2=0, rlog=False)

Error:

    Traceback (most recent call last):
      File "fm_assist.py", line 34, in <module>
        model = fm.run(X_train, df_train['outcome'], X_test, df_test['outcome'])
      File "/Users/jilljenn/code/TF-recomm/venv/lib/python3.6/site-packages/pywFM/__init__.py", line 222, in run
        pairwise_interactions.append([float(x) for x in line.split(' ')])
      File "/Users/jilljenn/code/TF-recomm/venv/lib/python3.6/site-packages/pywFM/__init__.py", line 222, in <listcomp>
        pairwise_interactions.append([float(x) for x in line.split(' ')])
    ValueError: could not convert string to float:

**Comment by jfloff** [comment]
Could you provide a MWE so I can replicate better and try to debug?

Thank you for the report!

**Comment by jilljenn** [comment]
Sorry, the code was `k2=0` (I edited) but yes, I can provide a complete MWE.

**Comment by CherChen0** [comment]
Hello, I also met this problem, is it fixed?

**Comment by jfloff** [comment]
Could you guys use the [example](https://github.com/jfloff/pywFM/blob/master/examples/simple.py) do get a MWE working? I'm sorry, at the moment I'm a bit swamped with work and every help is appreciated :)

**Comment by CherChen0** [comment]
Sorry, what does "MWE" mean?
