### ISSUE TITLE
Problem on Windows Running toy example

### ISSUE THREAD

**Issue by fedro86** [jfloff/pywFM#3]
Hi,
I installed pywFM with in a Anaconda environment. I pip installed it right, then I set as environment variable LIBFM_PATH. Then I run the program: 

`

```
import pywFM
import numpy as np
import pandas as pd

features = np.matrix([
#     Users  |     Movies     |    Movie Ratings   | Time | Last Movies Rated
#    A  B  C | TI  NH  SW  ST | TI   NH   SW   ST  |      | TI  NH  SW  ST
    [1, 0, 0,  1,  0,  0,  0,   0.3, 0.3, 0.3, 0,     13,   0,  0,  0,  0 ],
    [1, 0, 0,  0,  1,  0,  0,   0.3, 0.3, 0.3, 0,     14,   1,  0,  0,  0 ],
    [1, 0, 0,  0,  0,  1,  0,   0.3, 0.3, 0.3, 0,     16,   0,  1,  0,  0 ],
    [0, 1, 0,  0,  0,  1,  0,   0,   0,   0.5, 0.5,   5,    0,  0,  0,  0 ],
    [0, 1, 0,  0,  0,  0,  1,   0,   0,   0.5, 0.5,   8,    0,  0,  1,  0 ],
    [0, 0, 1,  1,  0,  0,  0,   0.5, 0,   0.5, 0,     9,    0,  0,  0,  0 ],
    [0, 0, 1,  0,  0,  1,  0,   0.5, 0,   0.5, 0,     12,   1,  0,  0,  0 ]
])
target = [5, 3, 1, 4, 5, 1, 5]

fm = pywFM.FM(task='regression', num_iter=5)

# split features and target for train/test
# first 5 are train, last 2 are test
model = fm.run(features[:5], target[:5], features[5:], target[5:])
```

`

But the last line gives me an error:

```
"C:\Users\[...]\Anaconda\Lib\site-packages\pywFMlibFM" non è riconosciuto come comando interno o esterno, 
 un programma eseguibile o un file batch. (it means that it's not recognized as a internal or external command, an executable or a file batch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pywFM\__init__.py", line 230, in run
    rlog = pd.read_csv(rlog_path, sep='\t')
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pandas\io\parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pandas\io\parsers.py", line 275, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pandas\io\parsers.py", line 590, in __init__
    self._make_engine(self.engine)
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pandas\io\parsers.py", line 731, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\FedRo\Anaconda\lib\site-packages\pandas\io\parsers.py", line 1103, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 518, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:5030)
ValueError: No columns to parse from file
```

Could  you point me please where is the error? Thank you

**Comment by fedro86** [comment]
Solved. I set LIBFM_PATH --> C:\cygwin\home\FedRo\libfm-1.42.src\bin
instead of: C:\cygwin\home\FedRo\libfm-1.42.src\bin\

so it was trying to run C:\cygwin\home\FedRo\libfm-1.42.src\binlibFM instead C:\cygwin\home\FedRo\libfm-1.42.src\bin\libFM

Now there's another error, but this is another story

**Comment by jfloff** [comment]
:+1: Thank you for the report nonetheless, perhaps I can have a look at those dashes :)
